### ISSUE TITLE
"not in db" message for existing depicts statements

### ISSUE THREAD

**Issue by fuzheado** [EdwardBetts/depicts#4]
Looking at: [https://art.wikidata.link/item/Q29383733](https://art.wikidata.link/item/Q29383733)   (It's not a painting, but I tried it anyway.)

Somehow the list of existing depicts statements says:

this painting has 1 existing depicts statement
not in db (Q171023)   — 0 paintings

But the Q item does have an English label:

Trebonianus Gallus (Q171023)

**Comment by EdwardBetts** [comment]
The depicts tool includes a database of items that have been used as depicts statements in paintings. The message 'not in db' means this item had never been used with a painting.

I've changed the code so it will download the depicts item and add it to the database.
